### ISSUE TITLE
How does this thing even work?

### ISSUE THREAD

**Issue by thewhiterabbit** [terrafx/terrafx.interop.vulkan#51]
#### Tried to get this to work
I don't understand how this works.

I need an explanation of how this works, or how to get it working so I can try to use it.

TIA.

**Comment by tannergooding** [comment]
Could you please give an explanation of what you're having trouble with?

TerraFX.Interop.Vulkan is nearly 1-to-1 bindings for .NET of the Vulkan API.

https://www.vulkan.org/learn has many resources for learning Vulkan and much of the code will translate over to .NET fairly equivalently.

**Comment by SusuyoHashimoto** [comment]
How is this nearly 1-to-1 binding?

**Comment by tannergooding** [comment]
> How is this nearly 1-to-1 binding?

The bindings are as close to the C/C++ API surface as you can get in .NET

There is no renaming of types (only namespace placement not being "global"), the signatures are fully blittable and so there is no additional overhead (beyond the GC transition which isn't removable in most scenarios) or marshalling required to call into native.

There are many cases where the C/C++ code is simply a copy/paste into C# and a few fixups for syntax differences.

For example:
```cpp
#include <vulkan.h>

// other code

for (size_t i = 0; i < commandBuffers.size(); i++) {
    VkCommandBufferBeginInfo beginInfo{};
    beginInfo.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
    beginInfo.flags = 0; // Optional
    beginInfo.pInheritanceInfo = nullptr; // Optional

    if (vkBeginCommandBuffer(commandBuffers[i], &beginInfo) != VK_SUCCESS) {
        throw std::runtime_error("failed to begin recording command buffer!");
    }
}
```

becomes
```csharp
using TerraFX.Interop.Vulkan;
using static TerraFX.Interop.Vulkan.VkStructureType;
using static TerraFX.Interop.Vulkan.Vulkan;

// other code

for (int i = 0; i < commandBuffers.Length; i++) {
    VkCommandBufferBeginInfo beginInfo = default;
    beginInfo.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
    beginInfo.flags = 0; // Optional
    beginInfo.pInheritanceInfo = nullptr; // Optional

    if (vkBeginCommandBuffer(commandBuffers[i], &beginInfo) != VK_SUCCESS) {
        throw new Exception("failed to begin recording command buffer!");
    }
}
```

**Comment by tannergooding** [comment]
In comparison, many cases of .NET Bindings over native libraries will rename things to .NET naming conventions and use types which cannot be directly passed to native, such as string or array. This adds overhead on multiple levels and means that:
* The consumer cannot trivially follow existing C/C++ tutorials, which are the vast majority since Vulkan is natively written in C/C++
* The consumer must create a mental map of how the C/C++ names translate over to the .NET names
* The consumer is forced to take on the overhead of marshalling, which is undesirable for a lowlevel/high-performance API like Vulkan
* The bindings tend to be updated much more slowly as it requires manual effort to convert everything to .NET
* etc

TerraFX.Interop.Windows avoids most of these issues and minimizes the others giving rapid access to bindings that can be much more easily understood, consumed, updated, and published. Developers using TerraFX.Interop.Vulkan can rely on existing C/C++ tutorials, books, and resources and still achieve success and can get access to the latest version of bindings the day they come out (as it is an automated process to take the C headers and convert them to equivalent .NET code).

**Comment by thewhiterabbit** [comment]
How?

**Comment by tannergooding** [comment]
I'm sorry, I'm not sure what you're asking.

This is a standard .NET project and you would add a reference, as you would for almost any external dependency via NuGet: https://www.nuget.org/packages/TerraFX.Interop.Vulkan/1.2.198-rc2

If you are new to C#/.NET, then this project is likely not for you and I would suggest some learning resources here: http://dot.net/learn to get familiar with the language and how the project system works.

If you are new to Vulkan, I would suggest https://www.vulkan.org/learn which has the resources necessary to learn how to setup everything and render your first triangle. Vulkan, however, is not a beginner friendly API. It is very complex/lowlevel and requires a lot of manual management of resources and other things.
